spring:
  h2:
    console:
      path: /h2-console/semantic
      # enabled web
      enabled: true
    demo:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://bi-test-outside.mysql.rds.aliyuncs.com:6306/selection?serverTimezone=GMT%2B8&characterEncoding=utf8&useSSL=false # springboot2.0多数据源配置使用
    username: root
    password: Aa123456

server:
  port: 9080

authentication:
  enable: true
  exclude:
    path: /api/auth/user/register,/api/auth/user/login
  token:
    http:
      header:
        key: Authorization

semantic:
  url:
    prefix: http://127.0.0.1:9081

time:
  threshold: 100

mybatis:
  mapper-locations=classpath:mappers/custom/*.xml,classpath*:/mappers/*.xml


llm:
  parser:
    url:  http://127.0.0.1:9092
embedding:
  url: http://127.0.0.1:9092
functionCall:
  url: http://127.0.0.1:9092
